<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Code extends Model
{
    use HasFactory;
    protected $guarded = [];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        //get only events that are not with status 2
        static::addGlobalScope('deleted', function ($query) {
            $query->where('deleted', '!=', 1);
        });
    }
}
